In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


'C:\Users\swetha' is not recognized as an internal or external command,
operable program or batch file.


In [2]:
import numpy as np
 
arr1 = np.array([3, 2, 1])
arr2 = np.array([1, 2, 3])
   
print ("1st array : ", arr1)  
print ("2nd array : ", arr2)  
   
out_arr = np.add(arr1, arr2)  
print ("added array : ", out_arr)  

1st array :  [3 2 1]
2nd array :  [1 2 3]
added array :  [4 4 4]


In [4]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
b=np.array([[1,2,3],[4,5,6]])
print(b)
c=np.zeros((3,4))
print(c)
d=np.ones((2,2))
print(d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]]


In [5]:
import numpy as np
#add two arrays
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
print(c)

#multiply two arrays
d=np.array([[1,2],[3,4]])
e=np.array([[5,6],[7,8]])
f=d*e
print(f)

[5 7 9]
[[ 5 12]
 [21 32]]
